### ISSUE TITLE
Error while trying to send a request

### ISSUE THREAD

**Issue by ShrutiD** [OfficeDev/Outlook-Add-in-JavaScript-UseIdentityToken#1]
Hello,

I have successfully run the respective sample.
But while clicking on "Send Unique Exchange Id to Server" button in the add-in, i get the following error,
`makeServiceRequest @ Home.js:59serviceCallback @ Home.js:42(anonymous function) @ outlook-web-16.01.js:17rt @ outlook-web-16.01.js:17
VM974 Home.html?et=&_host_Info=Outlook|Web|16.01:1 XMLHttpRequest cannot load https://localhost:44311/api/IdentityToken/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44303' is therefore not allowed access. The response had HTTP status code 500.`

Also, the URL https://localhost:44311/api/IdentityToken/ when run, this error is displayed in the web browser,
Server Error in '/' Application.

Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'UseIdentityTokenService.WebApiApplication'.

Source Error: 

Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="UseIdentityTokenService.WebApiApplication" Language="C#" %>

Source File: /global.asax    Line: 1

Where am i going wrong? Please help.

**Comment by DianeD** [comment]
Hi @ShrutiD . Thanks for raising this issue. Sorry it took us so long to follow up on this. We will try to verify/reproduce the issue and respond here very soon.

**Comment by DianeD** [comment]
Hi @ShrutiD . After installing some missing dependencies, we were able to run the sample end-to-end, though not all attempts were successful. We've opened a work item to update it, but given how old the platforms of this sample are, it may be replaced or just removed. We can't give a time yet on when this decision will be made. Thanks again for reporting this!
